% function Fac = Gorkov(acoustic_contrast_factor,r,Eac,k,x)
% %UNTITLED2 Summary of this function goes here
% %   Detailed explanation goes here
% Fac = 4*pi*acoustic_contrast_factor*r*3*k*Eac*sin(k*x);
% end
         function Fac = Gorkov(c, rho_l, r, f_1, f_2,w,x,P_surface,k,T,damp_coeff,lambda,L,P_s,P_s2)

syms x

grad_p_in = -1/2*1i/T*(exp(4*x*(1i*pi+damp_coeff*lambda)/lambda)*(-4.8295*P_surface)^2 ...
-2*exp((damp_coeff*lambda*L+4*1i*pi*x+2*damp_coeff*x*lambda)/lambda)*(-4.8295*P_surface) ...
    *(P_surface*(1+4.2736))-exp(2*(-1i*lambda*T*w+damp_coeff*lambda*L+2*1i*pi*x)/lambda) ...
    *(P_surface*(1+4.2736))^2+2*exp((-2*1i*lambda*T*w+damp_coeff*lambda*L+4*1i*pi*x ...
    +2*damp_coeff*x*lambda)/lambda)*(P_surface*(1+4.2736))*(-4.8295*P_surface)...
    -exp(2*(-1i*lambda*T*w+2*1i*pi*x+2*damp_coeff*x*lambda)/lambda)*(-4.8295*P_surface)^2 ...
+(P_surface*(1+4.2736))^2*exp(2*(damp_coeff*lambda*L+2*1i*pi*x)/lambda))...
    *exp(-2*L*damp_coeff-2*damp_coeff*x)/w;


grad_v_in = -1/2/T*(8*1i*pi^2*exp((-2*1i*lambda*T*w+damp_coeff*lambda*L+4*1i*pi*x+2*damp_coeff*x*lambda)...
    /lambda)*P_s*P_s2-8*1i*pi^2*P_s*P_s2*exp((damp_coeff*lambda*L+4*1i*pi*x+2*damp_coeff*x*lambda)/lambda)...
    -1i*P_s^2*damp_coeff^2*lambda^2*exp(2*(damp_coeff*lambda*L+2*1i*pi*x)/lambda)+2*1i*exp((-2*1i*lambda*T*w ...
    +damp_coeff*lambda*L+4*1i*pi*x+2*damp_coeff*x*lambda)/lambda)*P_s*P_s2*damp_coeff^2*lambda^2+4*1i*pi^2 ...
    *P_s2^2*exp(4*x*(1i*pi+damp_coeff*lambda)/lambda)+4*pi*exp(2*(-1i*lambda*T*w+damp_coeff*lambda*L+2*1i*pi*x)...
    /lambda)*P_s^2*damp_coeff*lambda-4*pi*exp(2*(-1i*lambda*T*w+2*1i*pi*x+2*damp_coeff*x*lambda)/lambda)...
    *P_s2^2*damp_coeff*lambda-4*1i*pi^2*exp(2*(-1i*lambda*T*w+2*1i*pi*x+2*damp_coeff*x*lambda)/lambda)...
    *P_s2^2-1i*P_s2^2*damp_coeff^2*lambda^2*exp(4*x*(1i*pi+damp_coeff*lambda)/lambda)+4*1i*pi^2*P_s^2 ...
    *exp(2*(damp_coeff*lambda*L+2*1i*pi*x)/lambda)+1i*exp(2*(-1i*lambda*T*w+damp_coeff*lambda*L+2*1i*pi*x)...
    /lambda)*P_s^2*damp_coeff^2*lambda^2-2*1i*P_s*P_s2*damp_coeff^2*lambda^2*exp((damp_coeff*lambda*L+4*1i*pi ...
    *x+2*damp_coeff*x*lambda)/lambda)+4*exp(4*x*(1i*pi+damp_coeff*lambda)/lambda)*pi*P_s2^2*damp_coeff*lambda ...
    +1i*exp(2*(-1i*lambda*T*w+2*1i*pi*x+2*damp_coeff*x*lambda)/lambda)*P_s2^2*damp_coeff^2*lambda^2-4*1i ...
    *pi^2*exp(2*(-1i*lambda*T*w+damp_coeff*lambda*L+2*1i*pi*x)/lambda)*P_s^2-4*exp(2*(damp_coeff*lambda ...
    *L+2*1i*pi*x)/lambda)*pi*P_s^2*damp_coeff*lambda)*exp(-2*L*damp_coeff-2*damp_coeff*x)/w^3/lambda^2/rho_l^2;
Uac = 4*pi/3 * r^3 * (f_1 * 1/(2*rho_l*c^2) * real(grad_p_in) - f_2 * 3/4*rho_l*real(grad_v_in));
Fac=diff(Uac,x);

end